export const Characters = [
  {
    id: "bardock",
    name: "Bardock",
    description: "Son Goku's father",
    type: "h",
    race: "Sayayin",
    age: "23",
    status: "Dead",
  },
  {
    id: "gohan",
    name: "Son Gohan",
    description: "Goku's oldest son",
    type: "h",
    race: "Sayayin/Human",
    age: "23",
    status: "Alive",
  },
  {
    id: "goku",
    name: "Son Goku",
    description: "Protagonista de DB",
    type: "h",
    race: "Sayayin",
    age: "44",
    status: "Alive",
  },
  {
    id: "krillin",
    name: "Krillin",
    description: "Son Goku's best friend",
    type: "h",
    race: "Human",
    age: "44",
    status: "Alive",
  },
  {
    id: "majin_buu",
    name: "Majin Buu",
    description: "Enemy in the Boo Saga, in DBZ",
    type: "h",
    race: "Demon",
    age: "5 M",
    status: "Alive",
  },

  {
    id: "piccolo",
    name: "Piccolo",
    description: "Enemy and then friend of Son Goku",
    type: "h",
    race: "Namek",
    age: "27",
    status: "Alive",
  },
  {
    id: "vegeta",
    name: "Vegeta",
    description: "Sayayin prince",
    type: "h",
    race: "Sayayin",
    age: "48",
    status: "Alive",
  },
  {
    id: "bulma",
    name: "Bulma",
    description: "Vegeta's wife",
    type: "m",
    race: "Human",
    age: "47",
    status: "Alive",
  },
  {
    id: "caulifla",
    name: "Caulifla",
    description: "Saiyajin of Universe 6",
    type: "m",
    race: "Sayayin",
    age: "20",
    status: "Alive",
  },
  {
    id: "gine",
    name: "Gine",
    description: "Son Goku's mother",
    type: "m",
    race: "Sayayin",
    age: "25-30",
    status: "Dead",
  },
  {
    id: "milk",
    name: "Milk",
    description: "Son Goku's wife",
    type: "m",
    race: "Human",
    age: "47",
    status: "Alive",
  },
  {
    id: "no18",
    name: "Androide No. 18",
    description: "Krillin's wife",
    type: "m",
    race: "Android",
    age: "16",
    status: "Alive",
  },
  {
    id: "vados",
    name: "Vados",
    description: "Angel of Champa, god of destruction",
    type: "m",
    race: "Angel",
    age: "2 C",
    status: "Alive",
  },
  {
    id: "videl",
    name: "Videl",
    description: "Son Gohan's wife",
    type: "m",
    race: "Human",
    age: "23",
    status: "Alive",
  },
];
